apiVersion: apps/v1
kind: Deployment
metadata:
  name: easter-buddies
spec:
  selector:
    matchLabels:
      app: easter-buddies
  replicas: 1
  template:
    metadata:
      name: easter-buddies
      labels:
        app: easter-buddies
    spec:
      containers:
      - image: quay.io/cellgeni/easter_buddies:1.0
        imagePullPolicy: IfNotPresent
        name: easter-buddies
        ports:
        - containerPort: 8005
          name: easter-buddies
        resources:
          requests:
            memory: "256Mi"
            cpu: 1
          limits:
            memory: "512Mi"
            cpu: 2
        livenessProbe:
          httpGet:
            path: /
            port: easter-buddies
          initialDelaySeconds: 3
          timeoutSeconds: 5
          periodSeconds: 240

