apiVersion: v1
kind: Service
metadata:
  name: easter-buddies
  labels:
    app: easter-buddies
spec:
  type: NodePort
  ports:
  - port: 8005
    targetPort: easter-buddies
  selector:
    app: easter-buddies
